# We take the defaults except for treating as informational only.
# This provides feedback without erroring the entire CI pipeline.

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "*/tests/*"
# Remove path prefix for CodeCov processing on caf/decaf
fixes:
  - "/var/ci/_work/::"
