language: python

# manylinux2010 wheels are not found on xenial
dist: bionic

os:
  - linux

arch:
  - amd64

stages:
  - check
  - test
  - deploy

jobs:
  include:
    - python: 3.6
      env: TOXENV=clean,py36-stable,coveralls,report
    - python: 3.6
      env: TOXENV=py36-dev
    - python: 3.7
      env: TOXENV=py37-stable
    - python: 3.7
      env: TOXENV=py37-dev
    - python: 3.8
      env: TOXENV=py38-stable
    - python: 3.8
      env: TOXENV=py38-dev
    - python: 3.6
      env: TOXENV=check
    - python: 3.6
      env: TOXENV=docs

install:
  - pip install -U tox tox-travis sphinx

script: tox -v --skip-missing-interpreters false -e $TOXENV

before_deploy:
  - cd docs && sphinx-apidoc -f -o ./source ../src -H Modules && make html && touch build/html/.nojekyll

deploy:
  provider: pages:git
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: build/html/
  edge: true
  on:
    branch: master
