sudo: required
language: python
matrix:
  include:
    - python: 3.6
      env:
        - TOXENV=clean,py36-stable,coveralls,report
        - TOXENV=py36-dev
    - python: 3.7
      env:
        - TOXENV=py37-stable
        - TOXENV=py37-dev
    - python: 3.8
      env:
        - TOXENV=py38-stable
        - TOXENV=py38-dev
    # Some 3.9 depends are not yet avail, 11/06/2020.
    # - python: 3.9
    #   env:
    #     - TOXENV=py39-stable
    #     - TOXENV=py39-dev
    - env: TOXENV=check
    - env: TOXENV=docs
install:
  - pip install -U tox tox-travis

script: tox -v --skip-missing-interpreters false -e $TOXENV

before_deploy:
  - cd docs && sphinx-apidoc -f -o ./source ../src -H Modules && make html && touch build/html/.nojekyll

deploy:
  provider: pages:git
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: build/html/
  edge: true
  on:
    branch: master
