schedules:
- cron: "0 0 * * *" # cron syntax defining a schedule
  displayName: Daily Build
  branches:
    include:
    - master
    - develop
  always: true # Always run the Daily Build

jobs:
- job:
  displayName: ubuntu-22.04
  pool:
    vmImage: 'ubuntu-22.04'
  strategy:
    maxParallel: 4
    matrix:
      Python38:
        python.version: '3.8'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda env create --name myEnvironment --file environment.yml
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      pip install -e .[dev]
      pip freeze --all
      export MKL_THREADING_LAYER=GNU
      export OMP_NUM_THREADS=2
      python -c "import numpy; numpy.show_config()"
      pytest --durations=50 --random-order
    displayName: pytest

- job:
  displayName: ubuntu-20.04-open
  pool:
    vmImage: 'ubuntu-20.04'
  strategy:
    maxParallel: 4
    matrix:
      Python38:
        python.version: '3.8'
  timeoutInMinutes: 120 # how long to run the job before automatically cancelling

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: |
      conda env create --name open_env --file environment-openblas.yml
      source activate open_env
      pip install -e .[dev]
      pip freeze --all
      python -c "import numpy; numpy.show_config()"
    displayName: Create Anaconda environment

  - bash: |
      source activate open_env
      export MKL_THREADING_LAYER=GNU
      export OMP_NUM_THREADS=2
      pytest --durations=50 --random-order
    displayName: pytest

- job:
  displayName: ubuntu-20.04-intel
  pool:
    vmImage: 'ubuntu-20.04'
  strategy:
    maxParallel: 4
    matrix:
      Python38:
        python.version: '3.8'
  timeoutInMinutes: 120 # how long to run the job before automatically cancelling

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: |
      conda env create --name intel_env --file environment-intel.yml
      source activate intel_env
      pip install -e .[dev]
      pip freeze --all
      python -c "import numpy; numpy.show_config()"
    displayName: Create Anaconda environment

  - bash: |
      source activate intel_env
      export MKL_THREADING_LAYER=GNU
      export OMP_NUM_THREADS=2
      pytest --durations=50 --random-order
    displayName: pytest


- job:
  displayName: macOS-latest
  pool:
    vmImage: 'macOS-latest'
  strategy:
    maxParallel: 4
    matrix:
      Python38:
        python.version: '3.8'

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - bash: conda update -q -y conda
    displayName: Update conda

  - bash: conda clean -i -t -y
    displayName: Removing conda cached package tarballs.

  - bash: conda env create --name myEnvironment --file environment.yml
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      pip install -e .[dev]
      pip freeze --all
      python -c "import numpy; numpy.show_config()"      
      pytest --durations=50 -s
    displayName: pytest

- job:
  displayName: macOS-11
  pool:
    vmImage: 'macOS-11'
  strategy:
    maxParallel: 4
    matrix:
      Python38:
        python.version: '3.8'

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - bash: conda update -q -y conda
    displayName: Update conda

  - bash: conda clean -i -t -y
    displayName: Removing conda cached package tarballs.

  - bash: conda env create --name myEnvironment --file environment.yml
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      pip install -e .[dev]
      pip freeze --all
      python -c "import numpy; numpy.show_config()"      
      pytest --durations=50 -s
    displayName: pytest

- job:
  displayName: windows-latest
  pool:
    vmImage: 'windows-latest'
  strategy:
    maxParallel: 4
    matrix:
      Python38:
        python.version: '3.8'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda env create --name myEnvironment --file environment.yml
    displayName: Create Anaconda environment

  - script: conda update -q -y conda
    displayName: Update conda

  - script: |
      call activate myEnvironment
      pip install -e .[dev]
      pip freeze --all
      python -c "import numpy; numpy.show_config()"      
      pytest --durations=50 --random-order
    displayName: pytest
