jobs:
- job:
  displayName: ubuntu-16.04
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda update -q -y conda
    displayName: Update conda
    
  - bash: conda env create --name myEnvironment --file environment.yml
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      python setup.py install
      pytest tests
    displayName: pytest

- job:
  displayName: macOS-10.13
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

#  - bash: conda update -q -y conda
#    displayName: Update conda

  - bash: conda clean -i -t -y
    displayName: Removing conda cached package tarballs.
    
  - bash: conda env create --name myEnvironment --file environment.yml
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      python setup.py install
      pytest tests
    displayName: pytest

- job:
  displayName: vs2017-win2016
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda env create --name myEnvironment --file environment.yml
    displayName: Create Anaconda environment

  - script: conda update -q -y conda
    displayName: Update conda
    
  - script: |
      call activate myEnvironment
      python setup.py install
      pytest tests
    displayName: pytest
