schedules:
- cron: "0 0 * * *" # cron syntax defining a schedule
  displayName: Daily Build
  branches:
    include:
    - master
    - develop
  always: true # Always run the Daily Build

jobs:
- job:
  displayName: macOS-11
  pool:
    vmImage: 'macOS-11'
  strategy:
    maxParallel: 4
    matrix:
      Python38:
        python.version: '3.8'

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - bash: conda update -q -y conda
    displayName: Update conda

  - bash: conda clean -i -t -y
    displayName: Removing conda cached package tarballs.

  - bash: conda env create --name myEnvironment --file environment-default.yml
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      pip install -e .[dev]
      pip freeze --all
      python -c "import numpy; numpy.show_config()"      
      pytest --durations=50 -s
    displayName: pytest

- job:
  displayName: windows-latest
  pool:
    vmImage: 'windows-latest'
  strategy:
    maxParallel: 4
    matrix:
      Python38:
        python.version: '3.8'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda env create --name myEnvironment --file environment-default.yml
    displayName: Create Anaconda environment

  - script: conda update -q -y conda
    displayName: Update conda

  - script: |
      call activate myEnvironment
      pip install -e .[dev]
      pip freeze --all
      python -c "import numpy; numpy.show_config()"      
      pytest --durations=50 --random-order
    displayName: pytest
