name: 'aspire'

channels:
  - defaults
  - conda-forge

dependencies:
  - fftw
  - pyfftw
  - pip
  - python=3.8
  - numpy=1.21.5
  - pandas=1.3.5
  - scipy=1.7.3
  - scikit-learn
  - scikit-learn-intelex
  - scikit-image
  - mkl_fft
  - libblas=*=*mkl
  - pip:
    - .

