name: 'aspire'

channels:
  - conda-forge
  - defaults

dependencies:
  - pip
  - python=3.8
  - pyshtools
  - numpy=1.24.1
  - scipy=1.10.1
  - scikit-learn
  - scikit-image
  - libblas=*=*accelerate
