name: 'aspire'

channels:
  - defaults
  - conda-forge

dependencies:
  - make
  - wheel
  - python=3.6
  - numpy=1.15
  - scipy=1.1.0
  - fftw
  - pyfftw=0.10.4
  - pip=18.0
  - pybind11
  - click
  - matplotlib
  - pip:
    - mrcfile
    - console_progressbar
    - ipython
    - Sphinx==1.8.1
    - sphinx-rtd-theme
    - python-box
