name: ASPIRE Python Daily Build CI

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  dev_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Build Sphinx docs
        defaults:
	  run:
	    working-directory: ./docs
	run: |
	  make clean
	  sphinx-apidoc -f -o ./source ../src -H Modules
	  make html
	  